spring:
  redis:
    host: 192.168.59.100
    password: guo2056553678
    port: 6379
    database: 1
    lettuce:
      pool:
        max-active: 10
        min-idle: 2
        max-idle: 10
        max-wait: 1000ms


